name: jahwa_asset_management_system
description: 자화전자 자산관리 시스템.

# 다음은 앱 버전 및 빌드 번호를 정의합니다.
# 버전은 점으로 구분된 세개의 숫자입니다. (예: 1.2.43) 
# 그 다음 빌드 번호가 `+` 뒤에 표시됩니다. (옵션입니다.)
# 버전과 빌드 번호는 각각 --build-name과 --build-number를 지정하여 오버라이딩할 수 있습니다.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.4+15

publish_to: none

#모바일에 표시될 앱이름
flutter_launcher_name:
  name: "JAMS"

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  #다국어 처리
  
  flutter_localizations:
    sdk: flutter
  flutter_cupertino_localizations: ^1.0.1

  flutter_cupertino_settings: ^0.3.1
  
  # 다음은 앱에 Cupertino 아이콘 폰트를 추가합니다.
  # iOS 스타일 아이콘으로 CupertinoIcons 클래스를 이용해서 사용하세요.
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  
  #앱이 종료되어도 데이터 저장 처리
  shared_preferences: ^0.5.6+2

  #모바일 앱 이름 처리
  flutter_launcher_name: "^0.0.1"
  
  #Http API 통신
  http: ^0.12.2

  #퍼센트 표시되는 프로그래스 바
  percent_indicator: "^2.1.1"

  #QR 바코드 스캔
  barcode_scan: ^3.0.1

  #프로그레스바 UI
  progress_dialog: ^1.2.2
  
  #세팅 UI(Home 화면)
  settings_ui: ^0.2.0

  #알림 다이얼로그창
  rflutter_alert: ^1.0.3
  
  #provider
  provider: ^4.3.2+3

  #데이터 팝업 창
  flutter_picker: ^1.1.5

  #Bluetooth LE
  #라이선스 BSD
  #flutter_blue: ^0.7.2
  #flutter_bluetooth_serial : ^ 0.2.2
  #flutter_ble_lib: ^2.2.3

  #permission_handler: ^5.0.0+hotfix.3
  
  #설비관리 카드형태 리스트
  card_settings: 1.9.2

  font_awesome_flutter: ^8.8.1

  #package_info
  package_info: ^0.4.0+18

  #FloatingActionButton
  flutter_speed_dial: ^1.2.5

  searchable_dropdown: ^1.1.3

  search_widget: ^1.0.2
  
  #현지화 포멧(날짜, 성별..)
  intl: ^0.16.1
  #기본 브라우저로 웹사이트 띄우기
  url_launcher: ^5.4.10

  #shark btprotocol
  btprotocol: 
    path: ../jahwa_plugin/rfid/btprotocol

  #async: ^2.8.2
    
dev_dependencies:
  flutter_test:
    sdk: flutter

dependency_overrides:
  intl: ^0.17.0-nullsafety.2
    


  #다국어처리
  #intl_translation: ^0.17.1

# 이 파일의 일반적인 Dart에 관한 내용은 다음 페이지를 참고하세요.
# https://www.dartlang.org/tools/pub/pubspec
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# 아래 내용은 플러터에만 해당합니다.
# The following section is specific to Flutter.
flutter:

  # 다음 라인은 머티리얼 아이콘 폰트가 앱에 포함됨을 의미하며 
  # 머티리얼 아이콘의 Icons 클래스를 사용할 수 있습니다.
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # 앱에 에셋을 추가하려면 다음과 같이 에셋 섹션을 추가하세요.
  assets:
    - lib/lang/ko.json
    - lib/lang/vi.json
    - lib/assets/image/logo.png
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg
  # 이미지 에셋은 하나 이상의 해상도별 종류를 참조할 수 있습니다.
  # https://flutter.io/assets-and-images/#resolution-aware.
  # 패키지 의존성에 에셋을 추가하는 방법에 대한 자세한 내용은 아래 주소를 확인하세요.
  # https://flutter.io/assets-and-images/#from-packages
  # 앱에 사용자정의 폰트를 추가하려면 이 "flutter" 섹션에 폰트 섹션을 추가하세요.
  # 이 목록의 각 항목에는 폰트 패밀리 이름이 있는 "family" 키와 폰트의 에셋 및 
  # 기타 설명을 포함하는 "fonts" 키가 있어야합니다. 예를 들어,
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # 패키지 의존성의 폰트에 대한 자세한 내용은 아래 링크를 참조하세요.
  # https://flutter.io/custom-fonts/#from-packages
  
  
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
